### PR TITLE
Add Replicate demo and API

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @frank-xwang! 👋 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open-source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can run your model! View it here: https://replicate.com/cjwbw/cutler

Replicate also have an API, so people can easily run your model from their code:

```
import replicate
model = replicate.models.get("cjwbw/cutler")
model.predict(image=...)
```

Facebookresearch already has a few demo pages on Replicate [here](https://replicate.com/facebookresearch), and we would like to transfer this page to facebookresearch account too so you can modify and update the page, let us know!

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by frank-xwang** [comment]
Hello @chenxwh, 

Thank you for submitting your pull request and for creating demos for us. Could you please move the "predict.py" file into the "maskcut" folder? This would help keep all MaskCut-related files organized in the same location, as "predict.py" is primarily used for running MaskCut. Thank you.

Thank you!
Xudong

**Comment by chenxwh** [comment]
Hi Xudong,

Thanks for the suggestion, just updated the files!

**Comment by frank-xwang** [comment]
Thank you! Merged.

**Comment by chenxwh** [comment]
Thanks for merging! The page is now under `facebookresearch` org on Replicate https://replicate.com/facebookresearch/cutler, free feel to update and modify the page :D

**Comment by frank-xwang** [comment]
Got it! Thanks!

**Pull request merged**
